#!/bin/bash

make properclean
# git checkout . && git clean -xdf in all repositories would be fine too
rm -rf /.kraftcache /.unikraft/libs /.unikraft/unikraft
kraft list update
kraft list pull flexos-microbenchmarks@staging iperf@staging newlib@staging \
		tlsf@staging flexos-example@staging lwip@staging redis@staging \
		unikraft@staging pthread-embedded@staging nginx@staging
