$(eval $(call addlib,appsqlite))

APPSQLITE_SRCS-y += $(APPSQLITE_BASE)/main.c
APPSQLITE_CINCLUDES-y += -I$(APPSQLITE_BASE)/include

APPSQLITE_ASFLAGS += -g -target aarch64-none-elf -march=morello
APPSQLITE_CFLAGS += -g -target aarch64-none-elf -march=morello -mabi=aapcs
